baseurl = "https://wrentarohowell.com/"
#baseurl = "https://wonderful-wescoff-cddc75.netlify.app/"
metaDataFormat = "yaml"
title = "Wren Howell"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Wren"
      introSubtitle = "I am a security analyst/programmer and this is my page where I write about security, technology, and some other topics I am interested in. "
      introPhoto = "/picture.jpg"
      logo = "/blist-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

  # [[languages.en.menu.main]]
     #   name = "Tags"
    #    url = "tags"
    #    weight = 3

   # [[languages.en.menu.main]]
    #    name = "Top Post"
    #    url = "/en/blog/emoji-support/"
    #    weight = 4

  

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Wren Howell· All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "My people say I don't bite"
  twitter = "https://twitter.com/lotusninja2"
  linkedin = "https://www.linkedin.com/in/wren-h-b61141100/"
  #xing = "https://www.xing.com/profile/"
  #github = "https://github.com/"
  #medium = "https://medium.com/"
  #reddit = "https://reddit.com/"
  #dribbble = "https://dribbble.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
